### ISSUE TITLE
Py2, Py3, and byte strings

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-algorithms#226]
The title of this issue is probably too generic, but the problem is too. A number of fixes were submitted a year or so ago to make Geomag-Algorithms Python 3 friendly, many related to so-called "byte strings" in Py3.

The following is a sample call of the geomag.py command line program that breaks under Python 3 (it just works in Python 2):

```
538 <~/Data/Intermagnet/QuasiDefinitive/OneMinute> geomag.py --input iaga2002 --input-url 'file://./{date:%Y}/{date:%m}/{obs}{date:%Y%m%d}{t}{i}.{i}' --observatory BOU --inchannels X Y Z F --interval minute --type quasi-definitive --starttime 2017-09-01T00:00:00 --endtime 2017-09-01T23:59:00 --output edge --output-host mage1
Traceback (most recent call last):
  File "/Users/erigler/local/bin/geomag.py", line 18, in <module>
    main(args)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/Controller.py", line 498, in main
    _main(args)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/Controller.py", line 528, in _main
    controller.run(args)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/Controller.py", line 187, in run
    channels=output_channels)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/edge/EdgeFactory.py", line 202, in put_timeseries
    interval, starttime, endtime)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/edge/EdgeFactory.py", line 679, in _put_channel
    ric.send_trace(interval, trace_send)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/edge/RawInputClient.py", line 196, in send_trace
    buf = self._get_data(trace_send.data, starttime, samplerate)
  File "/Users/erigler/Devel/Python/geomag-algorithms/geomagio/edge/RawInputClient.py", line 327, in _get_data
    *samples)
struct.error: argument for 's' must be a bytes object
```

This ultimately came from:

https://github.com/usgs/geomag-algorithms/blob/fa638251d7d080fb9a0ba1b4fefb1a58c24d039e/geomagio/edge/RawInputClient.py#L322-L328

and the problem should be fixed by changing the way `packStr` is constructed. I'm guessing that prepending a `b` to the string will fix things in Py3.

I'll get around to submitting a PR for this soon if nobody beats me to it, but more importantly, I wanted to initiate a discussion to see if there is a good way to go about finding and fixing similar issues.

@jmfee-usgs @aclaycomb-usgs

**Comment by jmfee-usgs** [comment]
The python 3 version is running, so I believe this is fixed.
